# 모든 시간은 초 단위, 각 행=1초 가정과 호환
resources:
  conveyor: 1  # 동시 처리 수
  lifter: 1

steps:
  conveyor_in_s: 20     # 컨베이어 반입
  lifter_in_s: 10       # 리프터로 튜브 안착
  process_s: 1800       # 공정 진행(기본값) — 필요시 CLI에서 오버라이드
  lifter_out_s: 10      # 언로딩(리프터)
  conveyor_to_cool_s: 15
  cooling_store_s: 5

tubes:
  count: 6

power:
  per_tube_w: 2000      # 히터 1튜브 정격(W), 필요시 리스트로 [T1..T6]